/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tito' at '12/24/18 8:06 AM' with Gradle 2.6
 *
 * @author tito, @date 12/24/18 8:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
